---
- name: Use python3
  set_fact: ansible_python_interpreter=/usr/bin/python3

- name: "Create web directories to store the test results"
  file:
    path: "{{ dirs }}"
    state: directory
  with_items:
    - "{{ test_directory }}/{{ git_repository_name }}/web"
    - "{{ test_directory }}/{{ git_repository_name }}/web/cypress"
    - "{{ test_directory }}/{{ git_repository_name }}/web/gatling"
  loop_control:
    loop_var: dirs

- name: "Stop any running webresults containers"
  docker_container:
    name: webresults
    state: absent

# https://hub.docker.com/r/halverneus/static-file-server/tags?page=1&ordering=last_updated
- name: "Serve web results of testing via http://{{ inventory_hostname }}:8000"
  docker_container:
    name: webresults
    image: halverneus/static-file-server:v1.8.2
    volumes:
      - "{{ test_directory }}/{{ git_repository_name }}/web:/web:ro"
    ports:
      - "8000:8080"

#https://hub.docker.com/r/cypress/included/tags?page=1&ordering=last_updated
- name: "Docker pull cypress/included container image of 2,9 gigabyte if not done yet."
  docker_image:
    name: cypress/included:7.1.0
    source: pull

# https://github.com/cypress-io/cypress/issues/350
# Do not fail immediately. Otherwise, the results are not copied in the next task.
- name: "Run cypress tests and make video recordings. This may take some time."
  shell: "docker run -it --rm --name cypress --ipc=host --network host -v $PWD:/e2e -w /e2e cypress/included:7.1.0"
  args:
    chdir: "{{ test_directory }}/{{ git_repository_name }}/src/test/cypress"
  register: cypress_result
  ignore_errors: True

- name: "Copy cypress results to {{ test_directory }}/{{ git_repository_name }}/web/cypress directory"
  copy:
    src: "{{ test_directory }}/{{ git_repository_name }}/src/test/cypress/cypress/artifacts/"
    dest: "{{ test_directory }}/{{ git_repository_name }}/web/cypress"
    remote_src: yes

- name: "Run gatling tests"
  shell: "docker run -it --name gatling --ipc=host --network host -v $PWD:/gatling -w /gatling openjdk:8-jdk-alpine ./mvnw gatling:test && docker rm gatling"
  args:
    chdir: "{{ test_directory }}/{{ git_repository_name }}"

- name: "Copy gatling results to {{ test_directory }}/{{ git_repository_name }}/web/gatling directory"
  shell: "cp -r {{ test_directory }}/{{ git_repository_name }}/src/test/gatling/results/demoapp-*/* {{ test_directory }}/{{ git_repository_name }}/web/gatling"

- name: "Check if cypress tests failed."
  fail:
    msg: "The cypress test(s) have failed."
  when: cypress_result.rc == 1
 
