---
- name: Application deployment
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Download and deploy application
      import_role:
        name: download_and_deploy_application
