#!/usr/bin/env python

import os
import json

# Set your AWS credentials
os.environ['AWS_ACCESS_KEY_ID'] = ${{ secrets.AWS_ACCESS_KEY_ID }}
os.environ['AWS_SECRET_ACCESS_KEY'] = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
os.environ['AWS_DEFAULT_REGION'] = ${{ secrets.AWS_REGION }}

# Use the aws ec2 describe-instances command to get instance details
cmd = 'aws ec2 describe-instances --filters "Name=tag:Name,Values=gitlab-instance" "Name=instance-state-name,Values=running"'
result = os.popen(cmd).read()

# Parse the output and create a dynamic inventory
instances = json.loads(result)['Reservations'][0]['Instances']
inventory = {"gitlab_instance": {"hosts": [instances[0]['PublicIpAddress']]}}

# Print the dynamic inventory as JSON
print(json.dumps(inventory))
