---
- name: Create EC2 Instances
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch EC2 Instances 1
      ec2_instance:
        key_name: cdaas
        instance_type: t3.medium
        image_id: ami-04e601abe3e1a910f
        region: eu-central-1
        security_group: sg-0405acf0e36e7984d
        count: 1
        tags:
          Name: gitlab-master
        wait: yes
      register: ec2_master

    - name: Launch EC2 Instances 2
      ec2_instance:
        key_name: cdaas
        instance_type: t3.medium
        image_id: ami-04e601abe3e1a910f
        region: eu-central-1
        security_group: sg-0405acf0e36e7984d
        count: 1
        tags:
          Name: gitlab-runner
        wait: yes
      register: ec2_runner

    - name: Add new instances to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: launched
      with_items: "{{ ec2_master.instances + ec2_runner.instances }}"

- name: Wait for SSH to be available
  hosts: launched
  become: yes
  become_user: ubuntu
  tasks:
    - name: Wait for SSH to be available
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 60
        timeout: 600
