name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.3
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          echo "Provisioning Infrastructure"
          terraform init
          terraform validate
          terraform plan
          terraform apply --auto-approve
        working-directory: ./platform
          
      - name: Export Terraform output
        id: tf
        run: |
          INSTANCES=($(terraform output -json CDAAS_instance_ids))
          echo "PUB_IP=${INSTANCES[0]}" >> $GITHUB_ENV
        working-directory: ./platform
        
      - name: Delay for 45 seconds
        run: sleep 45

      - name: Display Public IP
        run: |
          echo "Public IP: ${{ env.PUB_IP }}"
